import { Car, CarCategory } from './types';

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2023,
    category: CarCategory.ELECTRIC,
    pricePerDay: 180,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
    description: 'Experience the future of driving with insane acceleration and cutting-edge tech.',
    features: ['Autopilot', 'Premium Sound', 'Ludicrous Mode', 'Glass Roof'],
    hostName: 'Sarah J.',
    location: 'Los Angeles, CA',
    rating: 4.9,
    trips: 42
  },
  {
    id: '2',
    make: 'Porsche',
    model: '911 Carrera',
    year: 2022,
    category: CarCategory.SPORT,
    pricePerDay: 250,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    description: 'The definitive sports car experience. Perfect for weekend getaways.',
    features: ['Sport Chrono', 'Bose Audio', 'Heated Seats', 'Sunroof'],
    hostName: 'Michael R.',
    location: 'Miami, FL',
    rating: 5.0,
    trips: 15
  },
  {
    id: '3',
    make: 'Land Rover',
    model: 'Defender 110',
    year: 2023,
    category: CarCategory.SUV,
    pricePerDay: 165,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=800',
    description: 'Rugged luxury for any terrain. Spacious and capable.',
    features: ['4WD', 'Off-road Pack', '360 Camera', 'Air Suspension'],
    hostName: 'David K.',
    location: 'Denver, CO',
    rating: 4.8,
    trips: 28
  },
  {
    id: '4',
    make: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    category: CarCategory.SPORT,
    pricePerDay: 210,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&q=80&w=800',
    description: 'Precision engineering meets aggressive styling. A true drivers car.',
    features: ['M-Sport Exhaust', 'Carbon Fiber Trim', 'Track Mode', 'Heads-up Display'],
    hostName: 'Alex M.',
    location: 'San Francisco, CA',
    rating: 4.9,
    trips: 12
  },
  {
    id: '5',
    make: 'Mercedes-Benz',
    model: 'G-Wagon G63',
    year: 2023,
    category: CarCategory.LUXURY,
    pricePerDay: 450,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&q=80&w=800',
    description: 'The ultimate status symbol. Unmatched presence and luxury.',
    features: ['V8 Biturbo', 'Massage Seats', 'Night Package', 'Burmester Sound'],
    hostName: 'Vip Rentals',
    location: 'Beverly Hills, CA',
    rating: 5.0,
    trips: 8
  },
  {
    id: '6',
    make: 'Rivian',
    model: 'R1S',
    year: 2023,
    category: CarCategory.ELECTRIC,
    pricePerDay: 195,
    depositAmount: 500,
    image: 'https://images.unsplash.com/photo-1669023414166-a4cc7c0fe1f5?auto=format&fit=crop&q=80&w=800',
    description: 'The all-electric SUV that goes anywhere. Adventure ready.',
    features: ['Quad-Motor', 'Camp Mode', 'Gear Tunnel', 'Panoramic Roof'],
    hostName: 'Adventure Co.',
    location: 'Seattle, WA',
    rating: 4.7,
    trips: 35
  }
];
